-------------------------------------------------- ATIVIDADE 8 --------------------------------------------------
SELECT
    p.nome,
    pc.data_cadastro
FROM
    pessoa p
JOIN paciente pc
    ON pc.pessoa_id = p.id;

-------------------------------------------------- ATIVIDADE 9 --------------------------------------------------
SELECT
    p.nome,
    m.crm,
    e.nome AS especialidade
FROM
    pessoa p
JOIN medico m
    ON m.pessoa_id = p.id
JOIN especialidade e
    ON m.especialidade_id = e.id;

-------------------------------------------------- ATIVIDADE 10 --------------------------------------------------
SELECT id, logradouro, numero, complemento, bairro, cidade, uf, cep FROM pessoa;

CREATE TABLE endereco (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    cep VARCHAR(10),
    
    UNIQUE(logradouro, numero)
);

INSERT INTO endereco (
    logradouro, 
    numero, 
    complemento, 
    bairro, 
    cidade, 
    uf, 
    cep
)
SELECT DISTINCT
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    uf,
    cep
FROM 
    pessoa;

ALTER TABLE 
    pessoa
ADD COLUMN 
    endereco_id INT;

ALTER TABLE 
    pessoa
ADD CONSTRAINT 
    fk_pessoa_endereco
FOREIGN KEY (endereco_id) REFERENCES endereco(id);

UPDATE 
    pessoa p
SET 
    endereco_id = e.id
FROM 
    endereco e
WHERE
    (p.logradouro = e.logradouro OR (p.logradouro IS NULL AND e.logradouro IS NULL))
    AND
    (p.numero = e.numero OR (p.numero IS NULL AND e.numero IS NULL));

-- NÃO FOI EXECUTADO
ALTER TABLE pessoa
DROP COLUMN logradouro,
DROP COLUMN numero,
DROP COLUMN complemento,
DROP COLUMN bairro,
DROP COLUMN cidade,
DROP COLUMN uf,
DROP COLUMN cep;

SELECT
    p.nome,
    e.logradouro,
    e.numero
FROM
    pessoa p
JOIN endereco e
    ON p.endereco_id = e.id;

-------------------------------------------------- ATIVIDADE 11 --------------------------------------------------
SELECT
    p.id AS pessoa_id,
    p.nome,
    p.cpf,
    c.medico_id,
    c.data_consulta
FROM
    pessoa p
LEFT JOIN consulta c
    ON c.paciente_id = p.id
ORDER BY
    p.id;

SELECT
    p.id AS pessoa_id,
    p.nome,
    p.cpf,
    c.medico_id,
    c.data_consulta
FROM
    pessoa p
RIGHT JOIN consulta c
    ON c.paciente_id = p.id
ORDER BY
    p.id;

-------------------------------------------------- ATIVIDADE 12 --------------------------------------------------
SELECT
    m.pessoa_id AS medico_id,
    m.crm,
    c.data_consulta,
    c.paciente_id
FROM
    medico m
INNER JOIN consulta c
    ON c.medico_id = m.pessoa_id
ORDER BY
    m.pessoa_id;

SELECT
    m.pessoa_id AS medico_id,
    m.crm,
    c.data_consulta,
    c.paciente_id
FROM
    medico m
RIGHT JOIN consulta c
    ON c.medico_id = m.pessoa_id
ORDER BY
    m.pessoa_id;

SELECT
    pc.pessoa_id AS paciente_id,
    pc.numero_cartao,
    c.data_consulta,
    c.medico_id
FROM
    paciente pc    
INNER JOIN consulta c
    ON c.paciente_id = pc.pessoa_id
ORDER BY
    pc.pessoa_id;

SELECT
    pc.pessoa_id AS paciente_id,
    pc.numero_cartao,
    c.data_consulta,
    c.medico_id
FROM
    paciente pc    
RIGHT JOIN consulta c
    ON c.paciente_id = pc.pessoa_id
ORDER BY
    pc.pessoa_id;
