-- ATIVIDADE 8
SELECT
    p.nome,
    pc.data_cadastro
FROM
    pessoa p
JOIN paciente pc
    ON pc.pessoa_id = p.id;

-- ATIVIDADE 9
SELECT
    p.nome,
    m.crm,
    e.nome
FROM
    pessoa p
JOIN medico m
    ON m.pessoa_id = p.id
JOIN especialidade e
    ON m.especialidade_id = e.id;

-- ATIVIDADE 10
SELECT id, logradouro, numero, complemento, bairro, cidade, uf, cep FROM pessoa;

BEGIN;

CREATE TABLE endereco (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    cep VARCHAR(10),
    
    UNIQUE(logradouro, numero)
);

INSERT INTO endereco (logradouro, numero, complemento, bairro, cidade, uf, cep)
SELECT DISTINCT
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    uf,
    cep
FROM pessoa;

ALTER TABLE pessoa
ADD COLUMN endereco_id INT REFERENCES endereco(id);

UPDATE pessoa p
SET endereco_id = e.id
FROM endereco e
WHERE
    (p.logradouro = e.logradouro OR (p.logradouro IS NULL AND e.logradouro IS NULL))
    AND
    (p.numero = e.numero OR (p.numero IS NULL AND e.numero IS NULL));

ALTER TABLE pessoa
DROP COLUMN logradouro,
DROP COLUMN numero,
DROP COLUMN complemento,
DROP COLUMN bairro,
DROP COLUMN cidade,
DROP COLUMN uf,
DROP COLUMN cep;

COMMIT;

SELECT
    p.nome,
    e.logradouro,
    e.numero
FROM
    pessoa p
JOIN endereco e
    ON p.endereco_id = e.id;
