CREATE TABLE IF NOT EXISTS categorias (
    categoria_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT uq_categorias_nome UNIQUE (nome),
    CONSTRAINT ck_categorias_nome_nao_vazio CHECK (char_length(trim(nome)) > 0)
);

CREATE TABLE IF NOT EXISTS formas_pagamento (
    forma_pagamento_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    codigo_externo VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT uq_formas_pagamento_nome UNIQUE (nome),
    CONSTRAINT ck_formas_pagamento_nome_nao_vazio CHECK (char_length(trim(nome)) > 0)
);

CREATE TABLE IF NOT EXISTS lancamentos (
    lancamento_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT,
    valor NUMERIC(12,2) NOT NULL,
    data_lancamento DATE NOT NULL,
    categoria_id INT NOT NULL,
    forma_pagamento_id INT NOT NULL,
    observacao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT ck_lancamentos_valor_nao_negativo CHECK (valor >= 0),
    CONSTRAINT fk_lancamentos_categoria FOREIGN KEY (categoria_id)
        REFERENCES categorias (categoria_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_lancamentos_forma_pagamento FOREIGN KEY (forma_pagamento_id)
        REFERENCES formas_pagamento (forma_pagamento_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_lancamentos_categoria_id ON lancamentos (categoria_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_forma_pagamento_id ON lancamentos (forma_pagamento_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_data_valor ON lancamentos (data_lancamento, valor);

INSERT INTO 
    categorias (nome) 
VALUES
    ('Alimentação'),
    ('Transporte'),
    ('Energia Elétrica'),
    ('Água'),
    ('Internet');

INSERT INTO 
    formas_pagamento (nome) 
VALUES
    ('PIX'),
    ('Cartão de Crédito'),
    ('Débito'),
    ('Dinheiro');

INSERT INTO 
    lancamentos (descricao, valor, data_lancamento, categoria_id, forma_pagamento_id) 
VALUES
    ('Supermercado - Mercadão', 250.75, '2025-10-01', 1, 2),
    ('Conta de Luz - CEMIG', 120.40, '2025-09-25', 3, 3),
    ('Assinatura Internet', 99.90, '2025-09-30', 5, 2),
    ('Táxi aeroporto', 68.00, '2025-10-02', 2, 1);

UPDATE 
    lancamentos
SET 
    valor = ROUND(valor * 1.05, 2)
WHERE 
    data_lancamento < '2025-10-01';

UPDATE 
    lancamentos l
SET 
    valor = ROUND(l.valor * 0.98, 2)
FROM 
    formas_pagamento f
WHERE 
    l.forma_pagamento_id = f.forma_pagamento_id
    AND f.nome = 'PIX';

DELETE FROM 
    lancamentos
WHERE 
    descricao ILIKE '%teste%';